<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmbarcacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('embarcacions')->insert([
            'area_id' => '3',
            'user_id' => '1',
            'comercio_id' => '1',
            'category_id' => '1',
            'subcategory_id' => '3',
            'subcategories' => '4',
            'code' => 'B0001',
            'name' => 'EMBARCACIÓN DE CERCO',
            'image_path1' => 'amazona_foto1.jpg',
            'image_path2' => 'amazona_foto2.jpg',
            'image_path3' => 'amazona_foto3.jpg',
            'image_path4' => 'amazona_foto4.jpg',
            'video_path1' => '',
            'manufacturer_id' => '1',
            'details1' => '',
            'condition' => '',
            'eslora' => '65,31 MTS',
            'manga' => '11,00 MTS',
            'fe_fabricacion' => '1972',
            'color' => '',
            'material' => '',
            'maximumcrew' => '',
            'nroengines' => '',
            'anno_motor' => '',
            'enginebrand' => '',
            'enginemodel' => '',
            'enginetype' => '',
            'hoursofuse' => '',
            'power' => '',
            'estereo' => '',
            'negotiable' => '',
            'additional_information' => '',
            'currency' => '',
            'price1' => '1',
            'price2' => '1',
            'price_offer' => '1',
            'price_divisa' => '1',
            'stock_min' => '1',
            'stock_max' => '1',
            'stock' => '1',
            'in_pickup' => '0',
            'in_delivery' => '0',
            'in_envio_nacional' => '0',
            'madein' => '',
            'in_pedido' => '0',
            'in_offer' => '0',
            'ca_valoracion' => '5',
            'in_valido' => '1',
            'matricula' => 'APNN-PE-0212',
            'distintivollamada' => 'YYFB',
            'nroomi' => '7121138',
            'nrommsi' => '775 613 000',
            'armador' => 'PESQUERA AMAZONAS C.A.',
            'operador' => 'CHURUM MERU I.S.G. S.A.',
            'puntal' => '4,51 MTS',
            'arqueobruto' => '916,21 TON',
            'arqueoneto' => '313,89 TON',
            'capacidadcombustible' => '',
            'capacidadalmacenamiento' => '',
            'puertoregistro' => 'PUERTO SUCRE',
            'artepesca' => 'CERCO ATUNERO',
            'userCreated_at' => 1,
            'userUpdated_at' => 1,
            'created_at' => '2022-05-16 12:20:36',
            'updated_at' => '2022-05-16 12:20:36'
        ]);

        DB::table('embarcacions')->insert([
            'area_id' => '3',
            'user_id' => '1',
            'comercio_id' => '1',
            'category_id' => '1',
            'subcategory_id' => '4',
            'subcategories' => '5',
            'code' => 'B0002',
            'name' => 'PALANGRE ATUNERO',
            'image_path1' => 'roma_foto1.jpg',
            'image_path2' => 'roma_foto2.jpg',
            'image_path3' => 'roma_foto3.jpg',
            'image_path4' => 'roma_foto4.jpg',
            'video_path1' => '',
            'manufacturer_id' => '1',
            'details1' => '',
            'condition' => '',
            'eslora' => '',
            'manga' => '',
            'fe_fabricacion' => '2022-05-16',
            'color' => '',
            'material' => '',
            'maximumcrew' => '',
            'nroengines' => '',
            'anno_motor' => '',
            'enginebrand' => '',
            'enginemodel' => '',
            'enginetype' => '',
            'hoursofuse' => '',
            'power' => '',
            'estereo' => '',
            'negotiable' => '',
            'additional_information' => '',
            'currency' => '',
            'price1' => '1',
            'price2' => '1',
            'price_offer' => '1',
            'price_divisa' => '1',
            'stock_min' => '1',
            'stock_max' => '1',
            'stock' => '1',
            'in_pickup' => '0',
            'in_delivery' => '0',
            'in_envio_nacional' => '0',
            'madein' => '',
            'in_pedido' => '0',
            'in_offer' => '0',
            'ca_valoracion' => '5',
            'in_valido' => '1',
            'matricula' => '',
            'distintivollamada' => '',
            'nroomi' => '',
            'nrommsi' => '',
            'armador' => '',
            'puntal' => '',
            'arqueobruto' => '',
            'arqueoneto' => '',
            'capacidadcombustible' => '',
            'capacidadalmacenamiento' => '',
            'puertoregistro' => '',
            'artepesca' => '',
            'userCreated_at' => 1,
            'userUpdated_at' => 1,
            'created_at' => '2022-05-16 12:20:36',
            'updated_at' => '2022-05-16 12:20:36'
        ]);

        DB::table('embarcacions')->insert([
            'area_id' => '3',
            'user_id' => '1',
            'comercio_id' => '1',
            'category_id' => '1',
            'subcategory_id' => '1',
            'subcategories' => '1',
            'code' => 'B0003',
            'name' => 'PALANGRE ATUNERO',
            'image_path1' => 'dream_foto1.jpg',
            'image_path2' => 'dream_foto2.jpg',
            'image_path3' => 'dream_foto3.jpg',
            'image_path4' => '',
            'video_path1' => '',
            'manufacturer_id' => '1',
            'details1' => '',
            'condition' => '',
            'eslora' => '25,95 MTS',
            'manga' => '7,62 MTS',
            'fe_fabricacion' => '1996',
            'color' => '',
            'material' => '',
            'maximumcrew' => '',
            'nroengines' => '',
            'anno_motor' => '',
            'enginebrand' => '',
            'enginemodel' => '',
            'enginetype' => '',
            'hoursofuse' => '',
            'power' => '1300 HP',
            'estereo' => '',
            'negotiable' => '',
            'additional_information' => '',
            'currency' => '',
            'price1' => '1',
            'price2' => '1',
            'price_offer' => '1',
            'price_divisa' => '1',
            'stock_min' => '1',
            'stock_max' => '1',
            'stock' => '1',
            'in_pickup' => '0',
            'in_delivery' => '0',
            'in_envio_nacional' => '0',
            'madein' => '',
            'in_pedido' => '0',
            'in_offer' => '0',
            'ca_valoracion' => '5',
            'in_valido' => '1',
            'matricula' => 'ARSI-PE-0062',
            'distintivollamada' => 'YYP-5.817',
            'nroomi' => '8940141',
            'nrommsi' => '775993501',
            'armador' => 'LOREANNA PESCA C.A.',
            'puntal' => '3,81 MTS',
            'arqueobruto' => '147,91 MTS',
            'arqueoneto' => '66,56 MTS',
            'capacidadcombustible' => '120.360 LTS',
            'capacidadalmacenamiento' => '30 TON',
            'puertoregistro' => 'GUIRIA',
            'artepesca' => 'PALANGRE ATUNERO',
            'userCreated_at' => 1,
            'userUpdated_at' => 1,
            'created_at' => '2022-05-16 12:20:36',
            'updated_at' => '2022-05-16 12:20:36'
        ]);

        
    }
}
